# Generated by Django 5.2.17 on 2026-10-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
